
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Apr 08 23:22:11 CEST 2018
//----------------------------------------------------

package yal.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int FONCTION = 38;
  public static final int FSI = 34;
  public static final int TANTQUE = 30;
  public static final int MULT = 4;
  public static final int EGAL = 8;
  public static final int REPETER = 36;
  public static final int SI = 32;
  public static final int VIRGULE = 39;
  public static final int FIN = 26;
  public static final int LIRE = 37;
  public static final int LONGUEUR = 10;
  public static final int OU = 16;
  public static final int TYPE = 24;
  public static final int INF = 12;
  public static final int NON = 17;
  public static final int PAROUV = 6;
  public static final int DIV = 5;
  public static final int EGALEGAL = 13;
  public static final int PLUS = 2;
  public static final int DEBUT = 27;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int RETOURNE = 40;
  public static final int MOINS = 3;
  public static final int ET = 15;
  public static final int SINON = 33;
  public static final int IDF = 25;
  public static final int ALORS = 35;
  public static final int CROCHOUV = 20;
  public static final int PARFER = 7;
  public static final int CONSTANTEINT = 22;
  public static final int CONSTANTEBOOL = 23;
  public static final int POINT = 19;
  public static final int PROGRAMME = 9;
  public static final int POINTVIRGULE = 18;
  public static final int FINTANTQUE = 31;
  public static final int SUP = 11;
  public static final int DIFF = 14;
  public static final int CSTECHAINE = 29;
  public static final int CROCHFER = 21;
  public static final int ECRIRE = 28;
}

