/* The following code was generated by JFlex 1.6.1 */

package yal.analyse ;

import java_cup.runtime.*;
import yal.exceptions.AnalyseLexicaleException;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/yal/analyse/AnalyseurLexical.jflex</tt>
 */
public class AnalyseurLexical implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int commentaire = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\24\1\23\1\26\1\27\1\23\22\0\1\24\1\37\1\31"+
    "\5\0\1\42\1\43\1\30\1\34\1\32\1\35\1\0\1\25\12\17"+
    "\1\0\1\33\1\40\1\36\1\41\2\0\32\22\6\0\1\12\1\3"+
    "\1\44\1\1\1\2\1\14\1\11\1\22\1\15\2\22\1\45\1\13"+
    "\1\16\1\10\1\6\1\47\1\7\1\46\1\5\1\4\1\20\1\22"+
    "\1\21\2\22\12\0\1\26\u1fa2\0\1\26\1\26\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\12\2\1\3\1\2\1\4\1\5\1\6"+
    "\1\1\1\7\1\10\1\11\1\12\1\13\1\1\1\14"+
    "\1\15\1\16\1\17\2\2\1\4\1\2\1\20\5\2"+
    "\1\21\7\2\1\4\1\22\2\0\1\23\1\24\1\2"+
    "\1\25\1\26\12\2\1\27\1\30\1\31\1\2\1\32"+
    "\13\2\1\33\1\2\1\34\1\2\1\35\6\2\1\36"+
    "\2\2\1\37\1\40\1\41\6\2\1\42\2\2\1\43"+
    "\3\2\1\44\1\45\1\2\1\46\1\2\1\47";

  private static int [] zzUnpackAction() {
    int [] result = new int[118];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\50\0\120\0\170\0\240\0\310\0\360\0\u0118"+
    "\0\u0140\0\u0168\0\u0190\0\u01b8\0\u01e0\0\u0208\0\u0230\0\120"+
    "\0\u0258\0\120\0\u0280\0\120\0\120\0\120\0\120\0\u02a8"+
    "\0\u02d0\0\120\0\120\0\120\0\120\0\u02f8\0\u0320\0\u0348"+
    "\0\u0370\0\310\0\u0398\0\u03c0\0\u03e8\0\u0410\0\u0438\0\310"+
    "\0\u0460\0\u0488\0\u04b0\0\u04d8\0\u0500\0\u0528\0\u0550\0\u0578"+
    "\0\120\0\u05a0\0\u05c8\0\120\0\120\0\u05f0\0\u0618\0\120"+
    "\0\u0640\0\u0668\0\u0690\0\u06b8\0\u06e0\0\u0708\0\u0730\0\u0758"+
    "\0\u0780\0\u07a8\0\u07d0\0\310\0\310\0\u07f8\0\u05c8\0\u0820"+
    "\0\u0848\0\u0870\0\u0898\0\u08c0\0\u08e8\0\u0910\0\u0938\0\u0960"+
    "\0\u0988\0\u09b0\0\310\0\u09d8\0\310\0\u0a00\0\310\0\u0a28"+
    "\0\u0a50\0\u0a78\0\u0aa0\0\u0ac8\0\u0af0\0\310\0\u0b18\0\u0b40"+
    "\0\310\0\310\0\310\0\u0b68\0\u0b90\0\u0bb8\0\u0be0\0\u0c08"+
    "\0\u0c30\0\310\0\u0c58\0\u0c80\0\310\0\u0ca8\0\u0cd0\0\u0cf8"+
    "\0\310\0\310\0\u0d20\0\310\0\u0d48\0\310";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[118];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\2\6\1\7\1\10\1\11\1\12"+
    "\1\6\1\13\1\6\1\14\1\6\1\15\1\16\1\17"+
    "\2\6\2\20\1\21\1\0\1\20\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\6\1\36\1\37\1\6\26\20\2\0\1\40"+
    "\17\20\51\0\1\6\1\41\20\6\21\0\4\6\1\0"+
    "\4\6\1\42\10\6\1\43\4\6\21\0\1\44\3\6"+
    "\1\0\22\6\21\0\4\6\1\0\11\6\1\45\10\6"+
    "\21\0\4\6\1\0\6\6\1\46\13\6\21\0\4\6"+
    "\1\0\1\6\1\47\20\6\21\0\4\6\1\0\3\6"+
    "\1\50\16\6\21\0\4\6\1\0\22\6\21\0\1\6"+
    "\1\51\2\6\1\0\7\6\1\52\1\6\1\53\2\6"+
    "\1\54\5\6\21\0\2\6\1\55\1\6\1\0\7\6"+
    "\1\56\12\6\21\0\4\6\17\0\1\16\31\0\6\6"+
    "\1\57\13\6\21\0\4\6\25\0\1\60\2\0\1\61"+
    "\17\0\31\62\1\63\16\62\36\0\1\64\47\0\1\65"+
    "\12\0\14\6\1\66\5\6\21\0\4\6\1\0\14\6"+
    "\1\67\5\6\21\0\4\6\25\0\1\70\23\0\2\6"+
    "\1\71\17\6\21\0\4\6\1\0\4\6\1\72\15\6"+
    "\21\0\4\6\1\0\6\6\1\73\13\6\21\0\4\6"+
    "\1\0\15\6\1\74\4\6\21\0\4\6\1\0\7\6"+
    "\1\75\12\6\21\0\4\6\1\0\4\6\1\76\1\77"+
    "\14\6\21\0\4\6\1\0\7\6\1\100\12\6\21\0"+
    "\4\6\1\0\15\6\1\101\4\6\21\0\4\6\1\0"+
    "\3\6\1\102\16\6\21\0\4\6\1\0\15\6\1\103"+
    "\4\6\21\0\4\6\1\0\14\6\1\104\5\6\21\0"+
    "\4\6\1\0\15\6\1\105\4\6\21\0\4\6\1\0"+
    "\11\6\1\106\10\6\21\0\4\6\23\60\1\0\2\60"+
    "\2\0\20\60\31\62\1\107\16\62\31\0\1\62\17\0"+
    "\6\6\1\110\13\6\21\0\4\6\1\0\15\6\1\111"+
    "\4\6\21\0\4\6\1\0\3\6\1\112\16\6\21\0"+
    "\4\6\1\0\14\6\1\113\5\6\21\0\4\6\1\0"+
    "\14\6\1\114\5\6\21\0\4\6\1\0\4\6\1\115"+
    "\15\6\21\0\4\6\1\0\10\6\1\116\11\6\21\0"+
    "\4\6\1\0\7\6\1\117\12\6\21\0\4\6\1\0"+
    "\1\6\1\120\20\6\21\0\4\6\1\0\6\6\1\121"+
    "\13\6\21\0\4\6\1\0\22\6\21\0\1\122\3\6"+
    "\1\0\20\6\1\123\1\6\21\0\4\6\1\0\4\6"+
    "\1\124\15\6\21\0\4\6\1\0\14\6\1\123\5\6"+
    "\21\0\4\6\1\0\1\6\1\125\20\6\21\0\4\6"+
    "\1\0\7\6\1\126\12\6\21\0\4\6\1\0\4\6"+
    "\1\127\15\6\21\0\4\6\1\0\1\6\1\130\20\6"+
    "\21\0\4\6\1\0\6\6\1\131\13\6\21\0\4\6"+
    "\1\0\22\6\21\0\3\6\1\132\1\0\6\6\1\133"+
    "\13\6\21\0\4\6\1\0\3\6\1\134\16\6\21\0"+
    "\4\6\1\0\4\6\1\135\15\6\21\0\4\6\1\0"+
    "\22\6\21\0\2\6\1\136\1\6\1\0\4\6\1\137"+
    "\15\6\21\0\4\6\1\0\11\6\1\140\10\6\21\0"+
    "\4\6\1\0\15\6\1\141\4\6\21\0\4\6\1\0"+
    "\6\6\1\142\13\6\21\0\4\6\1\0\1\6\1\143"+
    "\20\6\21\0\4\6\1\0\3\6\1\144\16\6\21\0"+
    "\4\6\1\0\11\6\1\145\10\6\21\0\4\6\1\0"+
    "\6\6\1\146\13\6\21\0\4\6\1\0\1\6\1\147"+
    "\20\6\21\0\4\6\1\0\14\6\1\150\5\6\21\0"+
    "\4\6\1\0\15\6\1\151\4\6\21\0\4\6\1\0"+
    "\1\6\1\152\20\6\21\0\4\6\1\0\12\6\1\153"+
    "\7\6\21\0\4\6\1\0\15\6\1\154\4\6\21\0"+
    "\4\6\1\0\6\6\1\155\13\6\21\0\4\6\1\0"+
    "\7\6\1\156\12\6\21\0\4\6\1\0\4\6\1\157"+
    "\15\6\21\0\4\6\1\0\12\6\1\160\7\6\21\0"+
    "\4\6\1\0\1\6\1\161\20\6\21\0\4\6\1\0"+
    "\15\6\1\162\4\6\21\0\4\6\1\0\22\6\21\0"+
    "\3\6\1\163\1\0\1\6\1\164\20\6\21\0\4\6"+
    "\1\0\3\6\1\165\16\6\21\0\4\6\1\0\1\6"+
    "\1\166\20\6\21\0\4\6";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3440];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\14\1\1\11\1\1\1\11\1\1\4\11"+
    "\2\1\4\11\23\1\1\11\2\0\2\11\2\1\1\11"+
    "\76\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[118];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  private Symbol symbol(int type) {
	return new Symbol(type, yyline, yycolumn) ;
  }

  private Symbol symbol(int type, Object value) {
	return new Symbol(type, yyline, yycolumn, value) ;
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AnalyseurLexical(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 148) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {         return symbol(CodesLexicaux.EOF) ;
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new AnalyseLexicaleException(yyline, yycolumn, yytext()) ;
            }
          case 40: break;
          case 2: 
            { return symbol(CodesLexicaux.IDF, yytext());
            }
          case 41: break;
          case 3: 
            { return symbol(CodesLexicaux.CONSTANTEINT, yytext());
            }
          case 42: break;
          case 4: 
            { 
            }
          case 43: break;
          case 5: 
            { return symbol(CodesLexicaux.DIV);
            }
          case 44: break;
          case 6: 
            { return symbol(CodesLexicaux.MULT);
            }
          case 45: break;
          case 7: 
            { return symbol(CodesLexicaux.VIRGULE);
            }
          case 46: break;
          case 8: 
            { return symbol(CodesLexicaux.POINTVIRGULE);
            }
          case 47: break;
          case 9: 
            { return symbol(CodesLexicaux.PLUS);
            }
          case 48: break;
          case 10: 
            { return symbol(CodesLexicaux.MOINS);
            }
          case 49: break;
          case 11: 
            { return symbol(CodesLexicaux.EGAL);
            }
          case 50: break;
          case 12: 
            { return symbol(CodesLexicaux.INF);
            }
          case 51: break;
          case 13: 
            { return symbol(CodesLexicaux.SUP);
            }
          case 52: break;
          case 14: 
            { return symbol(CodesLexicaux.PAROUV);
            }
          case 53: break;
          case 15: 
            { return symbol(CodesLexicaux.PARFER);
            }
          case 54: break;
          case 16: 
            { return symbol(CodesLexicaux.ET);
            }
          case 55: break;
          case 17: 
            { return symbol(CodesLexicaux.OU);
            }
          case 56: break;
          case 18: 
            { yybegin(commentaire);
            }
          case 57: break;
          case 19: 
            { return symbol(CodesLexicaux.EGALEGAL);
            }
          case 58: break;
          case 20: 
            { return symbol(CodesLexicaux.DIFF);
            }
          case 59: break;
          case 21: 
            { return symbol(CodesLexicaux.SI, yytext());
            }
          case 60: break;
          case 22: 
            { yybegin(YYINITIAL);
            }
          case 61: break;
          case 23: 
            { return symbol(CodesLexicaux.FIN, yytext());
            }
          case 62: break;
          case 24: 
            { return symbol(CodesLexicaux.FSI, yytext());
            }
          case 63: break;
          case 25: 
            { return symbol(CodesLexicaux.NON);
            }
          case 64: break;
          case 26: 
            { return symbol(CodesLexicaux.CSTECHAINE,yytext());
            }
          case 65: break;
          case 27: 
            { return symbol(CodesLexicaux.CONSTANTEBOOL, yytext());
            }
          case 66: break;
          case 28: 
            { return symbol(CodesLexicaux.LIRE, yytext());
            }
          case 67: break;
          case 29: 
            { return symbol(CodesLexicaux.DEBUT, yytext());
            }
          case 68: break;
          case 30: 
            { return symbol(CodesLexicaux.ALORS, yytext());
            }
          case 69: break;
          case 31: 
            { return symbol(CodesLexicaux.SINON, yytext());
            }
          case 70: break;
          case 32: 
            { return symbol(CodesLexicaux.TYPE, yytext());
            }
          case 71: break;
          case 33: 
            { return symbol(CodesLexicaux.ECRIRE);
            }
          case 72: break;
          case 34: 
            { return symbol(CodesLexicaux.TANTQUE, yytext());
            }
          case 73: break;
          case 35: 
            { return symbol(CodesLexicaux.REPETER, yytext());
            }
          case 74: break;
          case 36: 
            { return symbol(CodesLexicaux.RETOURNE, yytext());
            }
          case 75: break;
          case 37: 
            { return symbol(CodesLexicaux.FONCTION, yytext());
            }
          case 76: break;
          case 38: 
            { return symbol(CodesLexicaux.PROGRAMME, yytext());
            }
          case 77: break;
          case 39: 
            { return symbol(CodesLexicaux.FINTANTQUE, yytext());
            }
          case 78: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
